package com.example.hotelmanagement.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "config")
public class Config {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "manage_salary_percentage", nullable = false)
    private Double manageSalaryPercentage; // Percentage of revenue allocated for managers' salaries

    @Column(name = "staff_salary_percentage", nullable = false)
    private Double staffSalaryPercentage; // Percentage of revenue allocated for staff salaries

    @Column(name = "cleaners_salary_percentage", nullable = false)
    private Double cleanersSalaryPercentage; // Percentage of revenue allocated for cleaners' salaries

    @Column(name = "manager_base_salary", nullable = false)
    private Double managerBaseSalary;

    @Column(name = "staff_base_salary", nullable = false)
    private Double staffBaseSalary;

    @Column(name = "cleaner_base_salary", nullable = false)
    private Double cleanerBaseSalary;

    @Column(name = "total_revenue", nullable = false)
    private Double totalRevenue; // Total revenue generated by the hotel

    @Column(name = "total_bookings", nullable = false)
    private Double totalBookings; // Total number of bookings made

    public Config() {}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getManageSalaryPercentage() {
        return manageSalaryPercentage;
    }

    public void setManageSalaryPercentage(Double manageSalaryPercentage) {
        this.manageSalaryPercentage = manageSalaryPercentage;
    }

    public Double getStaffSalaryPercentage() {
        return staffSalaryPercentage;
    }

    public void setStaffSalaryPercentage(Double staffSalaryPercentage) {
        this.staffSalaryPercentage = staffSalaryPercentage;
    }

    public Double getCleanersSalaryPercentage() {
        return cleanersSalaryPercentage;
    }

    public void setCleanersSalaryPercentage(Double cleanersSalaryPercentage) {
        this.cleanersSalaryPercentage = cleanersSalaryPercentage;
    }

    public Double getManagerBaseSalary() {
        return managerBaseSalary;
    }

    public void setManagerBaseSalary(Double managerBaseSalary) {
        this.managerBaseSalary = managerBaseSalary;
    }

    public Double getStaffBaseSalary() {
        return staffBaseSalary;
    }

    public void setStaffBaseSalary(Double staffBaseSalary) {
        this.staffBaseSalary = staffBaseSalary;
    }

    public Double getCleanerBaseSalary() {
        return cleanerBaseSalary;
    }

    public void setCleanerBaseSalary(Double cleanerBaseSalary) {
        this.cleanerBaseSalary = cleanerBaseSalary;
    }

    public Double getTotalRevenue() {
        return totalRevenue;
    }

    public void setTotalRevenue(Double totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    public Double getTotalBookings() {
        return totalBookings;
    }

    public void setTotalBookings(Double totalBookings) {
        this.totalBookings = totalBookings;
    }

    // Additional methods for validation or business logic (optional)
    public void incrementTotalRevenue(Double revenue) {
        this.totalRevenue += revenue;
    }

    public void incrementTotalBookings() {
        this.totalBookings += 1;
    }

    public Double calculateManagerSalary() {
        return (this.manageSalaryPercentage * this.totalRevenue) + this.managerBaseSalary;
    }

    public Double calculateStaffSalary() {
        return (this.staffSalaryPercentage * this.totalRevenue) + this.staffBaseSalary;
    }

    public Double calculateCleanerSalary() {
        return (this.cleanersSalaryPercentage * this.totalRevenue) + this.cleanerBaseSalary;
    }
}
